### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by rickycorte** [rickycorte/maki-web#1]
- [x] Minimal UI
- [x] Full dark theme
- [x] Submit with Enter key or direct button press
- [x] Improve readme
- [x] Add public api documentation

**Comment by rickycorte** [comment]
- [ ] Improve react code 
- [ ] Add proper routing to autofill data
